### PR TITLE
fix: unicode encoding

### PR DESCRIPTION
**Pull request by lemmon**
Fixes encoding within the PHP `DOMDocument` class including special characters and emojis.

### CODE REVIEW

**Comment by johannschopplich** [comment]
Thanks! I think it's time to drop the custom implementation in favor of `use Kirby\Toolkit\Dom`. Could you update the PR, please?

**Comment by johannschopplich** [comment]
Hey! Can you please update the PR based on my latest changes to replace the custom DOM class with Kirby's own `Dom` implementation? See https://github.com/johannschopplich/kirby-highlighter/commit/0e4404da1a324d2a26d14c9f4e37c294b5416014

**Comment by johannschopplich** [comment]
Maybe your issue is already resolved? Open for feedback. 🙏

**Comment by lemmon** [comment]
Yes, it is. 👌

**Pull request closed without merging**
